# defines.py -> mudar para config
ROBOT_RADIUS = int(90)

BALL_RADIUS = 15  # Raio da bola em metros
BALL_POSSESSION_DISTANCE = ROBOT_RADIUS + BALL_RADIUS + 50  # Distância de posse da bola
MIN_PASS_DISTANCE = 1000

MAX_SHOOT_DISTANCE = 1500
DISTANCE_PRESS_OPPONENT = 200
INFLUENCE_RADIUS = 500
